# A workflow to release XSan by manually trigger by repo/Actions.

name: Release

on:
  workflow_dispatch:
  workflow_call:

jobs:
  release:
    runs-on: ubuntu-22.04
    permissions:
      contents: write

    steps:
    - name: Checkout code
      # uses: actions/checkout@v4
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: Build XSan
      uses: ./.github/workflows/build
      with:
        build_type: Release
        llvm_version: '15'
        extra_cmake_args: -DSYSTEM_NAME_TO_PACK=x86_64-ubuntu-22.04

    - name: Archive Artifacts
      run: |
        cd build
        cmake --build . --target package
        mkdir -p artifacts
        cp -r XSan-*.tar.gz XSan-*.zip version.txt artifacts/
   
    - name: Display structure of downloaded files
      run: ls -R build/artifacts

    - name: Read version from file
      id: get_version
      run: echo "RELEASE_VERSION=$(cat build/artifacts/version.txt | tr -d '\n\r')" >> $GITHUB_ENV

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        # Use the version from the file as tag_name/name
        tag_name: ${{ env.RELEASE_VERSION }}
        name: Release ${{ env.RELEASE_VERSION }}
        body: |
          Official release for version ${{ env.RELEASE_VERSION }}.
          See attached assets for details.
        files: build/artifacts/XSan-*
