# A workflow to release XSan by manually trigger by repo/Actions.

name: Release

on:
  workflow_dispatch:

jobs:
  build:
    uses: Camsyn/XSan/.github/workflows/build.yml@dev-xsan
    with:
      require_build_artifacts: true
      build_type: Release
      os_list: '["ubuntu-22.04"]'

  release:
    runs-on: ubuntu-22.04
    needs: build
    permissions:
      contents: write

    steps:
    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        merge-multiple: true
        pattern: artifacts-${{ github.run_id }}-*
        path: artifacts
   
    - name: Display structure of downloaded files
      run: ls -R artifacts

    - name: Read version from file
      id: get_version
      run: echo "RELEASE_VERSION=$(cat artifacts/version.txt | tr -d '\n\r')" >> $GITHUB_ENV

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        # Use the version from the file as tag_name/name
        tag_name: ${{ env.RELEASE_VERSION }}
        name: Release ${{ env.RELEASE_VERSION }}
        body: |
          Official release for version ${{ env.RELEASE_VERSION }}.
          See attached assets for details.
        files: artifacts/XSan-*
