# A workflow to release XSan by manually trigger by repo/Actions.

name: Release

on:
  workflow_dispatch:

jobs:
  build:
    steps:
      - name: Checkout code
        # uses: actions/checkout@v4
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Build XSan
        uses: ./.github/workflows/build
        with:
          build_type: Release
          llvm_version: '15'

      - name: Archive Artifacts
        run: |
          cd build
          cmake --build . --target package
          cmake --build . --target package_source
          mkdir -p artifacts
          cp -r XSan-*.tar.gz XSan-*.zip version.txt artifacts/

      - name: Upload Artifacts
        uses: actions/upload-artifact@26f96dfa697d77e81fd5907df203aa23a56210a8 #v4.3.0
        with:
          path: build/artifacts
          name: artifacts-${{ github.run_id }}-ubuntu-22.04-llvm15
          retention-days: 7

  release:
    runs-on: ubuntu-22.04
    needs: build
    permissions:
      contents: write

    steps:
    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        merge-multiple: true
        pattern: artifacts-${{ github.run_id }}-*
        path: artifacts
   
    - name: Display structure of downloaded files
      run: ls -R artifacts

    - name: Read version from file
      id: get_version
      run: echo "RELEASE_VERSION=$(cat artifacts/version.txt | tr -d '\n\r')" >> $GITHUB_ENV

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        # Use the version from the file as tag_name/name
        tag_name: ${{ env.RELEASE_VERSION }}
        name: Release ${{ env.RELEASE_VERSION }}
        body: |
          Official release for version ${{ env.RELEASE_VERSION }}.
          See attached assets for details.
        files: artifacts/XSan-*-Linux*
